.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "POFILEFILL" "1" "06/30/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
POFileFill \- fill a file with entries already translated in other files
.SH "SYNOPSIS"
.HP 11
\fBPOFileFill\fR [\fIOPTION\fR] [\fI...\fR] [\fITARGET\ FILE\fR] [\fIFILE\fR] [\fI...\fR]
.SH "INTRODUCTION"
.PP
POFileFill
fills a file with entries already translated in other files.
.SH "COMMAND LINE OPTIONS"
.TP
\fB\-\-help\fR or \fB\-h\fR
show usage instructions
.SH "MORE INFORMATION"
.PP
gettext\-lint web page: http://gettext\-lint.sourceforge.net/
.SH "AUTHOR"
Pedro Morais. 
.br
<morais@kde.org>
