.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "POFILEEQUIV" "1" "08/16/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
POFileEquiv \- glossary generator
.SH "SYNOPSIS"
.HP 12
\fBPOFileEquiv\fR [\fIOPTION\fR] [\fI...\fR] [\fIFILE\fR] [\fI...\fR]
.SH "INTRODUCTION"
.PP
POFileEquiv
tries to generate a glossary based on a large enough sample of translations
.SH "COMMAND LINE OPTIONS"
.TP
\fB\-\-help\fR or \fB\-h\fR
show usage instructions
.TP
\fB\-\-max\fR or \fB\-m\fR
maximum number of translations to consider
.TP
\fB\-\-occurences\fR or \fB\-o\fR
minimum number of occurences of a translation
.TP
\fB\-\-ratio\fR or \fB\-r\fR
minimum ratio to best match to include a word
.SH "MORE INFORMATION"
.PP
gettext\-lint web page: http://gettext\-lint.sourceforge.net/
.SH "AUTHOR"
Pedro Morais. 
.br
<morais@kde.org>
