.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "POFILEGLOSSARY" "1" "08/16/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
POFileGlossary \- checks a collection of PO files against a glossary
.SH "SYNOPSIS"
.HP 15
\fBPOFileGlossary\fR [\fIOPTION\fR] [\fI...\fR] [\fIGLOSSARY\fR] [\fIFILE\fR] [\fI...\fR]
.SH "INTRODUCTION"
.PP
POFileGlossary
checks a collection of PO files against a glossary
.SH "COMMAND LINE OPTIONS"
.TP
\fB\-\-help\fR or \fB\-h\fR
show usage instructions
.TP
\fB\-\-overview\fR or \fB\-o\fR
generate an overview file, grouping by error and not by file
.SH "GLOSSARY FILE FORMAT"
.PP
Glossary files are in XML format.
.SH "MORE INFORMATION"
.PP
gettext\-lint web page: http://gettext\-lint.sourceforge.net/
.SH "AUTHOR"
Pedro Morais. 
.br
<morais@kde.org>
