.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "POFILESTATUS" "1" "06/30/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
POFileStatus \- validator and status reporting
.SH "SYNOPSIS"
.HP 13
\fBPOFileStatus\fR [\fIOPTION\fR] [\fI...\fR] [\fIFILE\fR] [\fI...\fR]
.SH "INTRODUCTION"
.PP
POFileStatus
validates files using
msgfmt
and reports its status.
.SH "COMMAND LINE OPTIONS"
.TP
\fB\-\-help\fR or \fB\-h\fR
show usage instructions
.TP
\fB\-\-show\-all\fR or \fB\-a\fR
show all files, even if 100% translated
.TP
\fB\-\-break\-path\fR or \fB\-b\fR
all file path componentes to the output; for example, for the file
\fIdir\fR/\fIfile.po\fR
the attributes
\fIname\-1="dir"\fR
and
\fIname\-2="file.po"\fR
would be added
.TP
\fB\-\-pot\-dir=\fR\fIdir\fR or \fB\-p \fR\fIdir\fR
use this pot templates dir to check if a po file is obsolete or if a pot file is completely untranslated
.TP
\fB\-\-pot\-exclude=\fR\fIpat\fR or \fB\-p \fR\fIpat\fR
exclude pot files that match this pattern; can be used multiple times
.SH "MORE INFORMATION"
.PP
gettext\-lint web page: http://gettext\-lint.sourceforge.net/
.SH "AUTHOR"
Pedro Morais. 
.br
<morais@kde.org>
