.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "POFILECHECKER" "1" "08/16/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
POFileChecker \- searches for common mistakes in PO/POT files
.SH "SYNOPSIS"
.HP 14
\fBPOFileChecker\fR [\fIOPTION\fR] [\fI...\fR] [\fIFILE\fR] [\fI...\fR]
.SH "INTRODUCTION"
.PP
POFileChecker
searches for common mistakes in PO/POT files.
.SH "COMMAND LINE OPTIONS"
.TP
\fB\-\-help\fR or \fB\-h\fR
show usage instructions
.TP
\fB\-\-pot\fR or \fB\-t\fR
check a pot file, not a po file
.TP
\fB\-\-ignore\-fuzzy\fR or \fB\-f\fR
don't check validity of fuzzy entries
.SH "PO FILE HEADER DIRECTIVES"
.PP
POFileChecker
recognizes several PO file header directives. As with all gettext lint tools, these directives are all prefixed with X\-POFile.
.TP
X\-POFile\-Allow: \fInumber\fR
number of errors to ignore; if number of detected errors is diffent than this they will all be reported; a file with 0 errors but an error allowance greater than zero will also be reported
.TP
X\-POFile\-CheckAccelerator: \fI1|0\fR
enable or disable checking accelerators, enabled by default
.TP
X\-POFile\-CheckEndPontuation: \fI1|0\fR
enable or disable checking ending pontuation, enabled by default
.TP
X\-POFile\-LineLength: \fInumber\fR
check that the line length doesn't exceed
\fInumber\fR
chars; disable by default
.SH "MORE INFORMATION"
.PP
gettext\-lint web page: http://gettext\-lint.sourceforge.net/
.SH "AUTHOR"
Pedro Morais. 
.br
<morais@kde.org>
